name: remove_from_coverage
description: A command-line tool to customize the contents of a coverage lcov.info file.
version: 1.0.7
homepage: https://github.com/jack-r-warren/remove_from_coverage
author: Jack Warren <jack@jackwarren.info>

executables:
  remove_from_coverage:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0